Repository jellysoo97/nanalmoa-FE, pull requests merged in 2024-10, with the labels that each got.

#32 [FEAT] 유저 상태 관리
  package.json
  src/api/auth/post-refresh-token.ts
  src/api/interceptors.ts
  src/api/users/get-user-me.ts
  src/components/schedule/EventContainer.tsx
  src/components/schedule/EventItem.tsx
  src/constants/api.ts
  src/hooks/use-user.ts
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LoginRedirectPage.tsx
  src/store/user.ts
  src/types/auth.ts
  src/utils/handle-token.ts
  yarn.lock
Labels: FEAT

#33 [FEAT] 일정 폼 구현
  package.json
  src/components/common/ScheduleForm/FieldComponents/BaseField.tsx
  src/components/common/ScheduleForm/FieldComponents/CategoryField.tsx
  src/components/common/ScheduleForm/FieldComponents/DateTimeField.tsx
  src/components/common/ScheduleForm/FieldComponents/TextInputField.tsx
  src/components/common/ScheduleForm/ScheduleForm.tsx
  src/components/icons/DownArrowIcon.tsx
  src/components/schedule/EventContainer.tsx
  src/pages/ScheduleDetailPage.tsx
  src/pages/create-schedule/DateCreatePage.tsx
  yarn.lock
Labels: FEAT

#36 [FEAT] 네이버 OAuth 연동
  src/App.tsx
  src/api/auth/get-naver-login.ts
  src/api/interceptors.ts
  src/api/users/get-user-me.ts
  src/api/users/get-users-me.ts
  src/assets/imgs/naverLogin.png
  src/components/schedule/EventContainer.tsx
  src/constants/api.ts
  src/hooks/use-user.ts
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/LoginRedirectPage.tsx
  src/store/user.ts
  src/types/auth.ts
  src/utils/handle-token.ts
Labels: FEAT

#39 [FIX] 랜딩페이지 리다이렉트 버그 픽스
  src/hooks/use-user.ts
  src/pages/LandingPage.tsx
Labels: BUG

#40 [FIX] 네이버 OAuth state 수정 및 토큰 재발급 요청 dto 수정
  src/api/interceptors.ts
  src/constants/api.ts
  src/pages/LoginPage.tsx
  src/pages/LoginRedirectPage.tsx
  src/types/auth.ts
  src/utils/generate-random-state.ts
  src/utils/handle-token.ts
Labels: FIX

#41 [FEAT] 월간 캘린더 구현 및 ScheduleForm 수정
  src/api/schedules/get-schedule-by-range.ts
  src/components/common/ScheduleForm/FieldComponents/CategoryField.tsx
  src/components/common/ScheduleForm/FieldComponents/DateTimeField.tsx
  src/components/common/ScheduleForm/FieldComponents/TextInputField.tsx
  src/components/common/ScheduleForm/FieldComponents/react-datepicker.css
  src/components/common/ScheduleForm/FieldComponents/react-select.css
  src/components/common/ScheduleForm/ScheduleForm.tsx
  src/components/schedule/CalendarView.tsx
  src/components/schedule/EventContainer.tsx
  src/constants/api.ts
  src/hooks/use-calendar.tsx
  src/hooks/use-range-schedule.ts
  src/pages/ScheduleDetailPage.tsx
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/types/category.ts
  src/types/common.ts
  src/types/schedules.ts
Labels: FEAT

#44 [DEPLOY] 241008 배포 테스트
  .github/workflows/deploy.yml
  src/components/create-schedule/MediaAnalysisResultCarousel.tsx
  src/pages/index.ts
  src/routes/AppRouter.tsx
Labels: FIX, DEPLOY

#47 [FEAT] 일정 폼 그룹, 반복, 메모 필드 구현
  src/components/common/ScheduleForm/FieldComponents/GroupField.tsx
  src/components/common/ScheduleForm/FieldComponents/RepetitionField.tsx
  src/components/common/ScheduleForm/FieldComponents/TextAreaField.tsx
  src/components/common/ScheduleForm/ScheduleForm.tsx
  src/components/create-schedule/RepititionSetModal.tsx
Labels: FEAT

#49 [CHORE] main 브랜치 github workflows 추가
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: CHORE

#56 [STYLE] 홈화면, 일정 폼 일부 디자인 수정
  .github/workflows/build.yml
  src/components/common/LoadingSpinner.tsx
  src/components/common/ScheduleForm/FieldComponents/BaseField.tsx
  src/components/common/schedule-form/ScheduleForm.tsx
  src/components/common/schedule-form/field-components/BaseField.tsx
  src/components/common/schedule-form/field-components/CategoryField.tsx
  src/components/common/schedule-form/field-components/DateTimeField.tsx
  src/components/common/schedule-form/field-components/GroupField.tsx
  src/components/common/schedule-form/field-components/RepetitionField.tsx
  src/components/common/schedule-form/field-components/TextAreaField.tsx
  src/components/common/schedule-form/field-components/TextInputField.tsx
  src/components/common/schedule-form/field-components/react-datepicker.css
  src/components/common/schedule-form/field-components/react-select.css
  src/components/create-schedule/SelectMethodModal.tsx
  src/components/create-schedule/audio/FailAudio.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/components/layout/Layout.tsx
  src/components/schedule/CalendarView.tsx
  src/components/schedule/DailyView.tsx
  src/components/schedule/EventContainer.tsx
  src/components/schedule/EventItem.tsx
  src/components/schedule/Tabs.tsx
  src/components/schedule/WeekdaySelector.tsx
  src/hooks/use-calendar.tsx
  src/hooks/use-window-size.ts
  src/pages/HomePage.tsx
  src/pages/ScheduleDetailPage.tsx
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/types/common.ts
  tailwind.config.js
Labels: STYLE

#57 [STYLE] 음성 일정 등록 디자인 수정
  src/assets/imgs/FailFace.png
  src/assets/imgs/MicAbout.png
  src/assets/imgs/MicOff.svg
  src/assets/imgs/MicOn.svg
  src/assets/imgs/PostFace.png
  src/assets/imgs/SuccessFace.png
  src/assets/imgs/calendar.png
  src/assets/imgs/calendarImg.png
  src/assets/imgs/error.png
  src/assets/imgs/event.png
  src/assets/imgs/microphone.png
  src/assets/imgs/success.png
  src/components/common/Button.tsx
  src/components/common/IconButton.tsx
  src/components/create-schedule/EditModal.tsx
  src/components/create-schedule/MediaAnalysisLoadingModal.tsx
  src/components/create-schedule/MoveStepButtons.tsx
  src/components/create-schedule/audio/AboutAudioStep.tsx
  src/components/create-schedule/audio/FailAudio.tsx
  src/components/create-schedule/audio/StartAudio.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/components/create-schedule/audio/SuccessPostAudio.tsx
  src/components/layout/Layout.tsx
  src/components/schedule/EventContainer.tsx
  src/pages/create-schedule/CreateAudioSchedulePage.tsx
Labels: STYLE

#54 [FEAT] 일정 수정, 삭제 기능 연결
  package.json
  src/api/schedules/delete-schedule.ts
  src/api/schedules/patch-schedule-update.ts
  src/components/common/Toast.tsx
  src/components/common/schedule-form/ScheduleForm.tsx
  src/components/common/schedule-form/field-components/DateTimeField.tsx
  src/components/icons/CloseIcon.tsx
  src/components/icons/PostUpdateIcon.tsx
  src/components/icons/TrashCanIcon.tsx
  src/components/schedule/EventItem.tsx
  src/constants/api.ts
  src/constants/schedules.ts
  src/pages/ScheduleDetailPage.tsx
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/types/schedules.ts
  yarn.lock
Labels: FEAT

#59 [FEAT] 사진 일정 등록 ui 및 로직 추가
  src/api/schedules/post-analyze-image.ts
  src/assets/imgs/camera.png
  src/components/create-schedule/MediaAnalysisResultCarousel.tsx
  src/components/create-schedule/audio/AboutAudioStep.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/components/create-schedule/photo/AnalysisResultStep.tsx
  src/components/create-schedule/photo/EditScheduleModal.tsx
  src/components/create-schedule/photo/InfoStep.tsx
  src/components/create-schedule/photo/RegisterResultStep.tsx
  src/components/create-schedule/photo/SelectOptions.tsx
  src/components/create-schedule/photo/UploadPhotoStep.tsx
  src/components/create-schedule/photo/index.ts
  src/components/icons/GalleryIcon.tsx
  src/components/icons/index.ts
  src/hooks/use-photo.ts
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/pages/create-schedule/CreatePhotoSchedulePage.tsx
  src/types/schedules.ts
  tailwind.config.js
Labels: FEAT

#62 [FEAT] 사용자 검색 컴포넌트 추가
  src/api/users/post-user-search.ts
  src/components/common/UserSelector.tsx
  src/constants/api.ts
  src/types/auth.ts
Labels: FEAT

#65 [FEAT] 회원가입 ui 및 api 연동
  .github/workflows/deploy.yml
  src/api/auth/post-login.ts
  src/api/auth/post-signup.ts
  src/api/auth/post-sms-code.ts
  src/api/auth/post-sms-verify.ts
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/constants/validation.ts
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/pages/index.ts
  src/routes/AppRouter.tsx
  src/types/auth.ts
Labels: FEAT

#67 [FEAT] 관리자 추가 및 보낸 요청 조회 기능 연결
  src/api/manager/get-manager-invitation-send.ts
  src/api/manager/post-manager-invitation.ts
  src/components/common/Modal.tsx
  src/components/common/UserMiniProfile.tsx
  src/components/common/UserSelector.tsx
  src/components/setting/Invitation.tsx
  src/components/setting/InvitationSection.tsx
  src/components/setting/InviteModal.tsx
  src/components/setting/SettingSection.tsx
  src/components/setting/SettingTitle.tsx
  src/constants/api.ts
  src/pages/setting/SettingManagerPage.tsx
  src/types/manager.ts
Labels: FEAT

#69 [FIX] schedule api parameter uuid 제거 및 baseAPI 변경
  src/api/schedules/delete-schedule.ts
  src/api/schedules/get-schedule-by-id.ts
  src/api/schedules/get-schedule-by-month.ts
  src/api/schedules/get-schedule-by-range.ts
  src/api/schedules/get-schedules.ts
  src/components/schedule/DailyView.tsx
  src/hooks/use-range-schedule.ts
Labels: FIX

#68 [FIX] 로그인 로직 수정
  src/api/mypage/post-mypage-auth.ts
  src/components/common/Button.tsx
  src/components/common/PhoneNumberInput.tsx
  src/components/common/index.ts
  src/hooks/use-timer.ts
  src/pages/ErrorBoundary.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/pages/SignupResultPage.tsx
  src/pages/index.ts
  src/routes/AppRouter.tsx
  src/routes/path.ts
  src/types/auth.ts
Labels: FIX

#71 [FEAT] 관리자 받은 초대 확인 및 수락, 거절, 취소 기능 연결
  src/api/manager/get-manager-invitation-received.ts
  src/api/manager/patch-manager-accept.ts
  src/api/manager/patch-manager-cancel.ts
  src/api/manager/patch-manager-reject.ts
  src/components/setting/Invitation.tsx
  src/components/setting/InvitationLayout.tsx
  src/components/setting/InvitationSection.tsx
  src/components/setting/InvitationsSection.tsx
  src/components/setting/ReceivedInvitation.tsx
  src/components/setting/SendedInvitation.tsx
  src/constants/api.ts
  src/pages/setting/SettingManagerPage.tsx
  src/types/manager.ts
Labels: FEAT

#73 [FIX] 운영 배포 스크립트 추가
  .dev.env
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .prod.env
Labels: FIX

#78 [FIX] 배포 스크립트 수정
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: FIX

#79 [FIX] 배포 스크립트 수정
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: FIX

#77 [FEAT] 반복 필드 UI 추가 및 일정 등록 관련 수정
  src/components/common/UserMiniProfile.tsx
  src/components/common/schedule-form/ScheduleForm.tsx
  src/components/common/schedule-form/field-components/DateTimeField.tsx
  src/components/common/schedule-form/field-components/GroupField.tsx
  src/components/common/schedule-form/field-components/RepetitionField.tsx
  src/components/common/schedule-form/field-components/RepititionSetModal.tsx
  src/components/create-schedule/RepititionSetModal.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/types/schedules.ts
Labels: FEAT

#86 [FEAT] 알림 기능 추가
  src/api/group/patch-group-accept.ts
  src/api/group/patch-group-reject.ts
  src/api/invitations/get-invitations-user.ts
  src/components/common/PhoneNumberInput.tsx
  src/components/common/notification/Notification.tsx
  src/components/common/notification/NotificationItem.tsx
  src/components/common/notification/PendingItem.tsx
  src/components/common/notification/SettledItem.tsx
  src/components/layout/Header.tsx
  src/constants/api.ts
  src/hooks/use-notification.ts
  src/pages/LoginPage.tsx
  src/types/group.ts
  src/types/invitations.ts
Labels: FEAT

#91 [FEAT] 관리자 기능 전반 및 관리자 일정 조회 기능 추가
  src/api/manager/delete-manager.ts
  src/api/manager/delete-subordinate.ts
  src/api/manager/get-my-managers.ts
  src/api/manager/get-my-subordinates.ts
  src/api/schedules/get-schedule-by-month.ts
  src/api/schedules/get-schedule-by-range.ts
  src/components/common/SideBar.tsx
  src/components/icons/ManagerIcon.tsx
  src/components/icons/RefreshIcon.tsx
  src/components/layout/Header.tsx
  src/components/schedule/CalendarView.tsx
  src/components/schedule/DailyView.tsx
  src/components/setting/InvitationLayout.tsx
  src/components/setting/ManagerItem.tsx
  src/components/setting/ReceivedInvitation.tsx
  src/components/setting/SendedInvitation.tsx
  src/components/setting/SettingTitle.tsx
  src/constants/api.ts
  src/hooks/use-calendar.tsx
  src/hooks/use-manager.ts
  src/hooks/use-range-schedule.ts
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/pages/setting/SettingManagerPage.tsx
  src/store/manager.ts
  src/types/manager.ts
Labels: FEAT

#92 [FEAT] 사진 분석 -> 일정 등록 로직 추가
  src/components/common/Modal.tsx
  src/components/common/schedule-form/ScheduleForm.tsx
  src/components/common/schedule-form/field-components/DateTimeField.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/components/create-schedule/photo/AnalysisResultStep.tsx
  src/components/create-schedule/photo/EditScheduleModal.tsx
  src/components/create-schedule/photo/InfoStep.tsx
  src/components/create-schedule/photo/PermissionModal.tsx
  src/components/create-schedule/photo/SelectOptions.tsx
  src/components/create-schedule/photo/UploadPhotoStep.tsx
  src/constants/schedules.ts
  src/hooks/use-photo.ts
  src/pages/ScheduleDetailPage.tsx
  src/pages/create-schedule/CreateManualSchedulePage.tsx
  src/pages/create-schedule/CreatePhotoSchedulePage.tsx
  src/types/schedules.ts
  src/utils/calculate-days-between.ts
  tsconfig.app.tsbuildinfo
Labels: FEAT, FIX

#94 [FIX] form label issue 제거 및 관리자 관리 용어 수정
  src/components/common/UserSelector.tsx
  src/components/common/schedule-form/field-components/BaseField.tsx
  src/components/common/schedule-form/field-components/CategoryField.tsx
  src/components/common/schedule-form/field-components/DateTimeField.tsx
  src/components/common/schedule-form/field-components/RepetitionField.tsx
  src/components/setting/InvitationsSection.tsx
  src/pages/setting/SettingManagerPage.tsx
Labels: FEAT, FIX

#95 [FIX] 에러 fix 및 스타일 수정
  src/pages/HomePage.tsx
  src/pages/setting/SettingManagerPage.tsx
Labels: CHORE, FIX

#96 [FIX] 카메라 권한 설정 로직 변경
  src/components/create-schedule/MediaAnalysisResultCarousel.tsx
  src/components/create-schedule/photo/InfoStep.tsx
  src/components/create-schedule/photo/PermissionModal.tsx
  src/components/create-schedule/photo/UploadPhotoStep.tsx
  src/constants/schedules.ts
  src/hooks/use-photo.ts
  src/pages/create-schedule/CreatePhotoSchedulePage.tsx
  src/utils/calculate-days-between.ts
Labels: FIX

#97 [FIX] 잘못 연결된 subordinateName -> managerName 으로 수정
  src/components/setting/ReceivedInvitation.tsx
Labels: FIX

#99 [FIX] 카메라 설정 수정
  src/components/create-schedule/photo/UploadPhotoStep.tsx
  src/hooks/use-photo.ts
Labels: FIX

#101 [FIX] 수정사항 반영
  src/components/create-schedule/MediaAnalysisResultCarousel.tsx
  src/components/create-schedule/audio/SuccessAudio.tsx
  src/components/group/CreateGroupModal.tsx
  src/components/group/GroupMemberList.tsx
  src/components/group/MyGroupList.tsx
  src/pages/create-schedule/CreateAudioSchedulePage.tsx
  src/pages/setting/SettingGroupDetailPage.tsx
Labels: FIX
